version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: measy
      POSTGRES_PASSWORD: example1234
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/db/migration/v0001_init.sql:/docker-entrypoint-initdb.d/v0001_init.sql
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge