version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: measy
      POSTGRES_PASSWORD: example1234
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/db/migration/v0001_init.sql:/docker-entrypoint-initdb.d/v0001_init.sql
    networks:
      - postgres-network

  postgres-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@measy.com
      PGADMIN_DEFAULT_PASSWORD: example1234
    ports:
      - 16543:80
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge