spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/measy?${custom.jdbc.options}
    username: admin
    password: example1234
    driver-class-name:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 2500
      max-lifetime: 250000
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
          fetch_size: 100
    open-in-view: false
    show-sql: true
